import type { ServiceConfigV1 } from "./config.js";
import type { ServicePaths } from "./paths.js";
import { ServiceRejection } from "./rejection.js";

const HEADER = "# Generated by orca panel install. Re-run it instead of editing this file.";

function noBreaks(what: string, value: string): string {
  if (/[\r\n\0]/.test(value)) throw new ServiceRejection("service-value-newline", `${what} contains a line break or NUL: ${JSON.stringify(value)}`);
  return value;
}

/** A /bin/sh word: single-quoted, ' written as '\''. */
export function shQuote(value: string): string {
  return `'${noBreaks("a run.sh word", value).replaceAll("'", "'\\''")}'`;
}

/** A systemd ExecStart word: double-quoted; \ and " backslashed, % → %%, $ → $$. */
export function systemdQuote(value: string): string {
  const escaped = noBreaks("a unit value", value).replace(/[\\"%$]/g, (c) => (c === "%" ? "%%" : c === "$" ? "$$" : `\\${c}`));
  return `"${escaped}"`;
}
const systemdPlain = (value: string): string => noBreaks("a unit value", value).replaceAll("%", "%%");

const XML: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" };
export function xmlEscape(value: string): string {
  return noBreaks("a plist string", value).replace(/[&<>"']/g, (c) => XML[c]!);
}

export function serviceCommand(config: ServiceConfigV1): string[] {
  return [config.node, config.entry, "panel", "run", "--service", ...config.args];
}

/** Plan D8: one format both /bin/sh and systemd EnvironmentFile= read the same way. */
export function renderServiceEnv(config: ServiceConfigV1): string {
  const out = [HEADER];
  for (const [key, value] of Object.entries(config.env)) {
    if (/["\\$`\r\n\0]/.test(value)) {
      throw new ServiceRejection("service-env-value-unsupported", `${key}: service.env is read by both /bin/sh and systemd, so a value cannot contain " \\ $ \` or a line break`);
    }
    out.push(`${key}="${value}"`);
  }
  return `${out.join("\n")}\n`;
}

export function renderRunSh(config: ServiceConfigV1, paths: ServicePaths): string {
  return `${["#!/bin/sh", HEADER, "set -a", `. ${shQuote(paths.envFile)}`, "set +a", `exec ${serviceCommand(config).map(shQuote).join(" ")}`].join("\n")}\n`;
}

/** Spec §4's keys. Depends on paths only: environment and arguments stay in service.env and run.sh (openclaw's layout). */
export function renderPlist(paths: ServicePaths): string {
  const s = (value: string): string => `<string>${xmlEscape(value)}</string>`;
  return `${[
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">', "<dict>",
    "  <key>Label</key>", `  ${s(paths.label)}`,
    "  <key>ProgramArguments</key>", "  <array>", `    ${s("/bin/sh")}`, `    ${s(paths.runScript)}`, "  </array>",
    "  <key>RunAtLoad</key>", "  <true/>",
    "  <key>KeepAlive</key>", "  <dict>", "    <key>SuccessfulExit</key>", "    <false/>", "  </dict>",
    "  <key>ThrottleInterval</key>", "  <integer>10</integer>",
    "  <key>ExitTimeOut</key>", "  <integer>20</integer>",
    "  <key>ProcessType</key>", `  ${s("Interactive")}`,
    "  <key>StandardInPath</key>", `  ${s("/dev/null")}`,
    "  <key>StandardOutPath</key>", `  ${s(paths.outLog)}`,
    "  <key>StandardErrorPath</key>", `  ${s(paths.errLog)}`,
    "  <key>WorkingDirectory</key>", `  ${s(paths.panelDir)}`,
    "  <key>SoftResourceLimits</key>", "  <dict>", "    <key>NumberOfFiles</key>", "    <integer>4096</integer>", "  </dict>",
    "</dict>", "</plist>",
  ].join("\n")}\n`;
}

/** Spec §4's unit, with plan D1 (Restart=on-failure) and D5 (absolute paths). */
export function renderUnit(config: ServiceConfigV1, paths: ServicePaths): string {
  return `${[
    HEADER, "[Unit]", "Description=Orca panel", "After=network-online.target", "Wants=network-online.target",
    "StartLimitBurst=10", "StartLimitIntervalSec=300", "",
    "[Service]", "Type=simple",
    `ExecStart=${serviceCommand(config).map(systemdQuote).join(" ")}`,
    `EnvironmentFile=${systemdPlain(paths.envFile)}`,
    `WorkingDirectory=${systemdPlain(paths.panelDir)}`,
    "Restart=on-failure", "RestartSec=5", "RestartPreventExitStatus=78", "SuccessExitStatus=0 143",
    "KillMode=mixed", "TimeoutStopSec=30", "LimitNOFILE=4096", "",
    "[Install]", "WantedBy=default.target",
  ].join("\n")}\n`;
}
