import { z } from "zod";
import type { ControlStore } from "./store.js";
import { artifactSchema } from "./schema.js";
import { readArtifact } from "./archive.js";
import { readCommittedCheckpoint } from "./checkpoints.js";
import { allWork, readGroup } from "./queries.js";
import { hashPayload } from "./commands.js";
import { ControlError } from "./errors.js";

const identitySchema=z.object({groupId:z.string(),workItemId:z.string(),taskId:z.string().nullable(),runId:z.string(),generation:z.number(),graphVersion:z.number(),targetVersion:z.number()}).strict();
const packetSchema=z.object({protocol:z.literal(1),identity:identitySchema,request:z.unknown().nullable(),runState:z.unknown(),completed:z.array(z.string()),unfinished:z.array(z.string()),pendingDecisions:z.array(z.string()),awaitingHuman:z.array(z.string()),validationCommands:z.array(z.string()),rawLogs:z.array(artifactSchema),usageHighWater:z.number().int().nonnegative(),unresolvedRequestIds:z.array(z.string()),artifacts:z.array(artifactSchema)}).strict();
function currentRuns(store:ControlStore,groupId:string){const rows=store.db.prepare("SELECT body FROM runs WHERE group_id=? ORDER BY rowid DESC").all(groupId).map(row=>JSON.parse(String(row.body)));const seen=new Set<string>();return rows.filter(run=>run.taskId&&run.checkpointId&&!seen.has(run.taskId)&&(seen.add(run.taskId),true));}
function markdownTask(data:any):Buffer{return Buffer.from(`# Task ${data.taskId} handoff\n\nCheckpoint: ${data.checkpointId}\nTarget version: ${data.targetVersion}\nResult: ${data.result}\n\n## Completed\n${data.completed.map((x:string)=>`- ${x}`).join("\n")||"- none"}\n\n## Unfinished\n${data.unfinished.map((x:string)=>`- ${x}`).join("\n")||"- none"}\n\n## Pending decisions\n${data.pendingDecisions.map((x:string)=>`- ${x}`).join("\n")||"- none"}\n\n## Awaiting human\n${data.awaitingHuman.map((x:string)=>`- ${x}`).join("\n")||"- none"}\n\n## Validation commands\n${data.validationCommands.map((x:string)=>`- ${x}`).join("\n")||"- none"}\n`);}
export async function buildTaskHandoff(store:ControlStore,groupId:string,taskId:string):Promise<{json:Buffer;markdown:Buffer}>{
 const run=currentRuns(store,groupId).find(value=>value.taskId===taskId);if(!run)throw new ControlError("task-checkpoint-not-committed");const candidate=await readCommittedCheckpoint(store,run.runId),packet=packetSchema.parse(JSON.parse((await readArtifact(store,candidate.handoff)).toString()));
 if(packet.identity.groupId!==groupId||packet.identity.workItemId!==candidate.workItemId||packet.identity.taskId!==taskId||packet.identity.runId!==run.runId||packet.identity.generation!==candidate.generation||packet.identity.graphVersion!==candidate.graphVersion||packet.identity.targetVersion!==candidate.targetVersion||packet.usageHighWater!==candidate.usageHighWater)throw new ControlError("handoff-identity-conflict");
 for(const ref of [...packet.rawLogs,...packet.artifacts])await readArtifact(store,ref);
 const group=readGroup(store,groupId),row=store.db.prepare("SELECT hash FROM checkpoints WHERE id=? AND run_id=?").get(candidate.checkpointId,run.runId);if(!row)throw new ControlError("checkpoint-not-committed");const events=store.db.prepare("SELECT body FROM usage_events WHERE run_id=? AND seq<=? ORDER BY seq").all(run.runId,candidate.usageHighWater).map(value=>JSON.parse(String(value.body)));
 const data={protocol:1,groupId,workItemId:candidate.workItemId,taskId,runId:run.runId,generation:candidate.generation,graphVersion:candidate.graphVersion,checkpointId:candidate.checkpointId,checkpointHash:String(row.hash),targetVersion:candidate.targetVersion,result:candidate.result,request:packet.request,unresolvedRequestIds:packet.unresolvedRequestIds,completed:packet.completed,unfinished:packet.unfinished,pendingDecisions:packet.pendingDecisions,awaitingHuman:packet.awaitingHuman,validationCommands:packet.validationCommands,rawLogs:[...packet.rawLogs].sort((a,b)=>a.artifactId.localeCompare(b.artifactId)),budgetLedger:{usageHighWater:candidate.usageHighWater,events},snapshot:candidate.snapshot,artifacts:[...candidate.artifacts].sort((a,b)=>a.artifactId.localeCompare(b.artifactId)),continuation:{groupId,taskId,expectedRevision:group.revision,predecessorRunId:run.runId,checkpointId:candidate.checkpointId,checkpointHash:String(row.hash)}};return {json:Buffer.from(JSON.stringify(data)),markdown:markdownTask(data)};
}
function markdownGroup(data:any):Buffer{return Buffer.from(`# Group ${data.groupId} handoff\n\nCheckpoint: ${data.groupCheckpointId}\nStatus: ${data.status}\n\n## Tasks\n${data.tasks.map((task:any)=>`- ${task.taskId}: ${task.status} (${task.reason}); checkpoint ${task.checkpointId??"none"}; impacts ${task.dependencyImpact.join(", ")||"none"}`).join("\n")}\n`);}
export async function buildGroupHandoff(store:ControlStore,groupId:string):Promise<{json:Buffer;markdown:Buffer}>{const group=readGroup(store,groupId),runs=currentRuns(store,groupId),work=allWork(store,groupId).filter(item=>item.taskId).sort((a,b)=>a.taskId!.localeCompare(b.taskId!));const refs=[] as Array<{taskId:string;checkpointId:string;checkpointHash:string}>;const tasks=[] as any[];
 for(const item of work){const run=runs.find(value=>value.taskId===item.taskId);let checkpointId:null|string=null,checkpointHash:null|string=null;if(run){const task=JSON.parse((await buildTaskHandoff(store,groupId,item.taskId!)).json.toString());checkpointId=task.checkpointId;checkpointHash=task.checkpointHash;refs.push({taskId:item.taskId!,checkpointId:task.checkpointId,checkpointHash:task.checkpointHash});}const dependencyImpact=work.filter(other=>other.dependsOn.includes(item.workItemId)).map(other=>other.taskId!).sort();tasks.push({taskId:item.taskId,workItemId:item.workItemId,targetVersion:item.targetVersion,status:item.status,reason:item.status==="ready"?"ready":item.status==="running"?"active-run":item.status==="blocked"?"checkpoint-blocked":"complete",dependsOn:[...item.dependsOn].sort(),dependencyImpact,checkpointId,checkpointHash});}
 const groupCheckpointId=hashPayload({groupId,revision:group.revision,budgetVersion:group.budgetVersion,taskCheckpointRefs:refs});const data={protocol:1,groupId,groupCheckpointId,revision:group.revision,budgetVersion:group.budgetVersion,status:group.status,stopped:group.stopped,used:group.used,reserved:group.reserved,limit:group.limit,taskCheckpointRefs:refs,tasks};return {json:Buffer.from(JSON.stringify(data)),markdown:markdownGroup(data)};}
