import { spawnSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import type { ServiceConfigV1 } from "../../src/service/config.js";
import { servicePaths } from "../../src/service/paths.js";
import { renderPlist, renderRunSh, renderServiceEnv, renderUnit, shQuote, systemdQuote, xmlEscape } from "../../src/service/render.js";

const roots: string[] = [];
afterEach(async () => { while (roots.length) await rm(roots.pop()!, { recursive: true, force: true }); });

const paths = servicePaths({
  ORCA_PANEL_DIR: "/home/ann/.orca/panel", ORCA_LAUNCH_AGENTS_DIR: "/home/ann/Library/LaunchAgents",
  ORCA_SYSTEMD_USER_DIR: "/home/ann/.config/systemd/user", ORCA_SERVICE_LABEL: "dev.orca.panel", ORCA_SERVICE_UNIT: "orca-panel",
});
const config: ServiceConfigV1 = {
  schema: "orca-panel-service-v1", node: "/opt/node/bin/node", entry: "/src/orca/dist/cli.js",
  args: ["--by", "ann", "--port", "7777", "--repo", "orca=/src/orca-web"],
  env: { HOME: "/home/ann", NODE_OPTIONS: "", ORCA_AGENTS_TABLE: "/home/ann/.orca/agents.json", ORCA_PANEL_DIR: "/home/ann/.orca/panel", PATH: "/opt/node/bin:/usr/bin:/bin" },
};
const lines = (...l: string[]) => `${l.join("\n")}\n`;
const HEADER = "# Generated by orca panel install. Re-run it instead of editing this file.";

describe("generated files (spec §3, §4)", () => {
  it("service.env: sorted KEY=\"value\" lines, no secrets anywhere else", () => {
    expect(renderServiceEnv(config)).toBe(lines(HEADER, 'HOME="/home/ann"', 'NODE_OPTIONS=""', 'ORCA_AGENTS_TABLE="/home/ann/.orca/agents.json"',
      'ORCA_PANEL_DIR="/home/ann/.orca/panel"', 'PATH="/opt/node/bin:/usr/bin:/bin"'));
  });

  it("run.sh sources service.env and execs node on dist/cli.js panel run --service", () => {
    expect(renderRunSh(config, paths)).toBe(lines("#!/bin/sh", HEADER, "set -a", ". '/home/ann/.orca/panel/service.env'", "set +a",
      "exec '/opt/node/bin/node' '/src/orca/dist/cli.js' 'panel' 'run' '--service' '--by' 'ann' '--port' '7777' '--repo' 'orca=/src/orca-web'"));
  });

  it("plist: the keys of spec §4, running /bin/sh run.sh, with no environment inline", () => {
    const plist = renderPlist(paths);
    expect(plist).toBe(lines(
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
      '<plist version="1.0">', "<dict>",
      "  <key>Label</key>", "  <string>dev.orca.panel</string>",
      "  <key>ProgramArguments</key>", "  <array>", "    <string>/bin/sh</string>", "    <string>/home/ann/.orca/panel/run.sh</string>", "  </array>",
      "  <key>RunAtLoad</key>", "  <true/>",
      "  <key>KeepAlive</key>", "  <dict>", "    <key>SuccessfulExit</key>", "    <false/>", "  </dict>",
      "  <key>ThrottleInterval</key>", "  <integer>10</integer>",
      "  <key>ExitTimeOut</key>", "  <integer>20</integer>",
      "  <key>ProcessType</key>", "  <string>Interactive</string>",
      "  <key>StandardInPath</key>", "  <string>/dev/null</string>",
      "  <key>StandardOutPath</key>", "  <string>/home/ann/.orca/panel/logs/panel.out.log</string>",
      "  <key>StandardErrorPath</key>", "  <string>/home/ann/.orca/panel/logs/panel.err.log</string>",
      "  <key>WorkingDirectory</key>", "  <string>/home/ann/.orca/panel</string>",
      "  <key>SoftResourceLimits</key>", "  <dict>", "    <key>NumberOfFiles</key>", "    <integer>4096</integer>", "  </dict>",
      "</dict>", "</plist>"));
    expect(plist).not.toContain("agents.json");
  });

  it("unit: spec §4 keys, Restart=on-failure (plan D1), absolute EnvironmentFile (plan D5)", () => {
    expect(renderUnit(config, paths)).toBe(lines(HEADER, "[Unit]", "Description=Orca panel", "After=network-online.target", "Wants=network-online.target",
      "StartLimitBurst=10", "StartLimitIntervalSec=300", "",
      "[Service]", "Type=simple",
      'ExecStart="/opt/node/bin/node" "/src/orca/dist/cli.js" "panel" "run" "--service" "--by" "ann" "--port" "7777" "--repo" "orca=/src/orca-web"',
      "EnvironmentFile=/home/ann/.orca/panel/service.env", "WorkingDirectory=/home/ann/.orca/panel",
      "Restart=on-failure", "RestartSec=5", "RestartPreventExitStatus=78", "SuccessExitStatus=0 143", "KillMode=mixed", "TimeoutStopSec=30", "LimitNOFILE=4096", "",
      "[Install]", "WantedBy=default.target"));
  });

  it("escapes per format and refuses line breaks everywhere", () => {
    expect(systemdQuote('50% "a" $HOME \\x')).toBe('"50%% \\"a\\" $$HOME \\\\x"');
    expect(shQuote("it's")).toBe("'it'\\''s'");
    expect(xmlEscape(`a&<b>"'`)).toBe("a&amp;&lt;b&gt;&quot;&apos;");
    const broken = { ...config, args: ["--by", "a\nb"] };
    for (const render of [() => renderUnit(broken, paths), () => renderRunSh(broken, paths)]) expect(render).toThrow(expect.objectContaining({ code: "service-value-newline" }));
    expect(() => renderPlist(servicePaths({ ORCA_PANEL_DIR: "/t/a\rb" }))).toThrow(expect.objectContaining({ code: "service-value-newline" }));
    for (const bad of ['a"b', "a\\b", "a$b", "a`b", "a\nb"]) {
      expect(() => renderServiceEnv({ ...config, env: { X: bad } })).toThrow(expect.objectContaining({ code: "service-env-value-unsupported" }));
    }
  });

  it("service.env sorts keys itself and refuses a key /bin/sh would run as a command", () => {
    const out = renderServiceEnv({ ...config, env: { Z: "1", A: "2", M: "3" } });
    expect(out).toBe(lines(HEADER, 'A="2"', 'M="3"', 'Z="1"'));
    for (const key of ["X Y", "A;rm", "1A", ""]) {
      expect(() => renderServiceEnv({ ...config, env: { [key]: "v" } })).toThrow(expect.objectContaining({ code: "service-config-invalid" }));
    }
  });

  it("unit escapes % and refuses line breaks in the two path lines (plan D5)", () => {
    const unit = renderUnit(config, servicePaths({ ORCA_PANEL_DIR: "/h/50%/panel" }));
    expect(unit).toContain("EnvironmentFile=/h/50%%/panel/service.env\n");
    expect(unit).toContain("WorkingDirectory=/h/50%%/panel\n");
    expect(() => renderUnit(config, servicePaths({ ORCA_PANEL_DIR: "/h/a\nExecStartPre=/bin/evil" }))).toThrow(expect.objectContaining({ code: "service-value-newline" }));
  });

  it("/bin/sh reads service.env and run.sh back exactly (spaces, quotes, % and # survive)", async () => {
    const root = await mkdtemp(join(tmpdir(), "rd-"));
    roots.push(root);
    const p = servicePaths({ ORCA_PANEL_DIR: root });
    const echo = join(root, "echo.mjs");
    await writeFile(echo, "process.stdout.write(JSON.stringify({ argv: process.argv.slice(2), x: process.env.X }));\n");
    const c: ServiceConfigV1 = { ...config, node: process.execPath, entry: echo, args: ["--by", "it's me", "--repo", "k=/a b/%c#d"], env: { X: "a b 'c' %d #e" } };
    await writeFile(p.envFile, renderServiceEnv(c));
    await writeFile(p.runScript, renderRunSh(c, p));
    const run = spawnSync("/bin/sh", [p.runScript], { encoding: "utf8", env: { PATH: "/usr/bin:/bin" } });
    expect(run.status, run.stderr).toBe(0);
    expect(JSON.parse(run.stdout)).toEqual({ argv: ["panel", "run", "--service", "--by", "it's me", "--repo", "k=/a b/%c#d"], x: "a b 'c' %d #e" });
  });

  it("the plist is valid for launchd's parser (macOS only; plutil is not launchctl)", async (ctx) => {
    if (process.platform !== "darwin") ctx.skip();
    const root = await mkdtemp(join(tmpdir(), "rp-"));
    roots.push(root);
    await writeFile(join(root, "x.plist"), renderPlist(paths));
    const lint = spawnSync("/usr/bin/plutil", ["-lint", join(root, "x.plist")], { encoding: "utf8" });
    expect(lint.status, lint.stdout + lint.stderr).toBe(0);
  });
});
