import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe,expect,it } from "vitest";
import { buildGroupHandoff,buildTaskHandoff } from "../../src/control/handoff.js";
import { commitCandidate } from "../../src/control/checkpoints.js";
import { publishPending } from "../../src/control/projection.js";
import { candidateCase } from "./fixtures/candidate.js";
import { setGroupStopped } from "../../src/control/commands.js";

describe("D3 handoff projections",{timeout:30000},()=>{
 it("builds task JSON from the committed packet and renders markdown without private claim fields",async()=>{const h=await candidateCase();try{await commitCandidate(h.store,h.candidate);const built=await buildTaskHandoff(h.store,"g1","T1"),json=JSON.parse(built.json.toString()),markdown=built.markdown.toString();
  expect(json).toMatchObject({protocol:1,groupId:"g1",workItemId:h.candidate.workItemId,taskId:"T1",runId:h.claim.runId,generation:h.candidate.generation,graphVersion:h.candidate.graphVersion,checkpointId:"cp1",targetVersion:1,unresolvedRequestIds:[],completed:["implemented"],unfinished:["follow-up"],pendingDecisions:["choose"],awaitingHuman:["approve"],validationCommands:["npm test"],continuation:{groupId:"g1",taskId:"T1",predecessorRunId:h.claim.runId,checkpointId:"cp1"}});expect(json.budgetLedger.events).toHaveLength(2);expect(json.snapshot.hash).toBe(h.candidate.snapshot?.hash);expect(markdown).toContain("follow-up");expect(markdown).not.toMatch(/ownerToken|owner-token|\bgrant\b/);
 }finally{await h.dispose();}});
 it("lists incomplete tasks with dependency impact and exact task checkpoint refs",async()=>{const h=await candidateCase();try{await commitCandidate(h.store,{...h.candidate,result:"partial",stopProof:null});const built=await buildGroupHandoff(h.store,"g1"),json=JSON.parse(built.json.toString());expect(json.tasks.map((task:{taskId:string})=>task.taskId)).toEqual(["T1","T2"]);expect(json.tasks[0]).toMatchObject({taskId:"T1",status:"blocked",checkpointId:"cp1"});expect(json.tasks[1]).toMatchObject({taskId:"T2",status:"ready",checkpointId:null});expect(json.groupCheckpointId).toMatch(/^[a-f0-9]{64}$/);
 }finally{await h.dispose();}});
 it("rebuilds committed projections and prevents an older replay from overwriting current handoffs",async()=>{const h=await candidateCase();try{await commitCandidate(h.store,{...h.candidate,result:"partial",stopProof:null});await publishPending(h.store);const oldGroup=String(h.store.db.prepare("SELECT id FROM outbox WHERE kind='group-handoff' AND body LIKE '%cp1%' ORDER BY rowid DESC LIMIT 1").get()?.id);await commitCandidate(h.store,{...h.candidate,checkpointId:"cp2"});await publishPending(h.store);const taskPath=join(h.store.stateDir,"exports","groups","g1","tasks","T1","handoff.md"),groupPath=join(h.store.stateDir,"exports","groups","g1","handoff.md"),current=await readFile(taskPath,"utf8"),currentGroup=await readFile(groupPath,"utf8");expect(current).toContain("cp2");h.store.db.prepare("UPDATE outbox SET delivered=0 WHERE id IN (?,?)").run("task-handoff:g1:T1:cp1",oldGroup);await publishPending(h.store);expect(await readFile(taskPath,"utf8")).toBe(current);expect(await readFile(groupPath,"utf8")).toBe(currentGroup);
 }finally{await h.dispose();}});
 it("does not hide a corrupt current checkpoint or roll back a committed run after projection failure",async()=>{const h=await candidateCase();try{await commitCandidate(h.store,h.candidate);await expect(publishPending(h.store,{writeProjection:async()=>{throw new Error("projection-write-failed");}})).rejects.toThrow("projection-write-failed");expect(h.store.db.prepare("SELECT active FROM runs WHERE id=?").get(h.claim.runId)?.active).toBe(0);await writeFile(join(h.store.stateDir,"checkpoints",h.claim.runId,"cp1.json"),"{}\n");await expect(buildTaskHandoff(h.store,"g1","T1")).rejects.toThrow("checkpoint-hash-mismatch");await expect(buildGroupHandoff(h.store,"g1")).rejects.toThrow("checkpoint-hash-mismatch");
 }finally{await h.dispose();}});
 it("publishes an immediate group handoff when the group is paused",async()=>{const h=await candidateCase();try{await commitCandidate(h.store,h.candidate);await publishPending(h.store);setGroupStopped(h.store,"g1",true,{commandId:"pause-group",expectedRevision:3,by:"human"});await publishPending(h.store);const json=JSON.parse((await buildGroupHandoff(h.store,"g1")).json.toString()),markdown=await readFile(join(h.store.stateDir,"exports","groups","g1","handoff.md"),"utf8");expect(json.stopped).toBe(true);expect(markdown).toContain(json.groupCheckpointId);
 }finally{await h.dispose();}});
});
